### ISSUE TITLE
Yanked from rubygems

### ISSUE THREAD

**Issue by jimbert** [pedgeio/lazy_loader_ruby#2]
We use a gem that has `lazy_loader` as a dependency. It's been [yanked from Rubygems](https://rubygems.org/gems/lazy_loader/) which is causing issues. 

Do you know what happened? Are there any plans to rerelease this gem?

**Comment by pedgeio** [comment]
I'd recommend commandeering it yourself - I haven't updated these in over five years, none of them should be used as they aren't maintained, if they're a dependency I would remove them honestly

**Comment by jimbert** [comment]
Cool, thanks for your response! We've removed the dependency :)

**Comment by benjamin-bader** [comment]
Out of curiosity, why yank the gem?

(of course, no obligation to respond, etc)

**Comment by pedgeio** [comment]
Fair question - I understand it might be annoying, but really just out of trying to clean up - I haven't maintained these in years, and if you're depending on them, that represents a potential risk. Likely you weren't even aware that you were depending on code that has not been maintained in a half-decade, and given that any use of this library is probably relatively fundamental (and easily replaced), it seemed better to me to not have it available than to keep it around, and force users to decide to maintain it themselves, or to replace it with another library.
